### ISSUE TITLE
AttributeError: 'VisRenderer' object has no attribute 'diff_vp' 

### ISSUE THREAD

**Issue by taivanbat** [silviazuffi/smalst#7]
I'm trying to visualize the model during training using visdom. I have set the `display_visuals ` flag to `True` in the `train_utils.py` file.

The error happens in line 551 of smal_shape.py. I am not able to find the function 'diff_vp' anywhere. 

This is the full error message: 

`
Traceback (most recent call last):
  File "/home/tk/.pycharm_helpers/pydev/pydevd.py", line 1432, in _exec
    runpy._run_module_as_main(module_name, alter_argv=False)
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/tk/smalst/experiments/smal_shape.py", line 625, in <module>
    app.run(main)
  File "/home/tk/smalst/.env/lib/python2.7/site-packages/absl/app.py", line 274, in run
    _run_main(main, argv)
  File "/home/tk/smalst/.env/lib/python2.7/site-packages/absl/app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "/home/tk/smalst/experiments/smal_shape.py", line 622, in main
    trainer.train()
  File "smalst/nnutils/train_utils.py", line 312, in train
    visualizer.display_current_results(self.get_current_visuals(), epoch)
  File "/home/tk/smalst/experiments/smal_shape.py", line 551, in get_current_visuals
    rend_frontal = self.vis_rend.diff_vp(self.pred_v[i], self.cam_pred[i], texture=texture_here, kp_verts=self.kp_verts[i])
AttributeError: 'VisRenderer' object has no attribute 'diff_vp'
`

Is there some code missing? How can I fix this? 

Thank you!

**Comment by silviazuffi** [comment]
Hi,

Sorry for that. It is code inherited from https://github.com/akanazawa/cmr <https://github.com/akanazawa/cmr>
I have not used the visualization, if there are missing functions you can find them in the repository above.

**Comment by taivanbat** [comment]
Thank you for the quick reply! I will do that
